### 一、异常

定义：异常（ Exception  也称例外）就是在程序的运行过程中 所发生的不正常的事件，它会中断正在运行的程序 

例如以下：

#### 1.1 运行时异常(RuntimeException)

- 算术异常 ArithmeticException 
- 空指针异常 NullPointerException 
- 类型转换异常 ClassCastException 
- 数组下标越界 ArrayIndexOutOfBoundsException 
- 期望的数据类型与实际输入类型不匹配 InputMismatchException

#### 1.2 检查时异常(Checked Exception)

- SQL Exception
- IOException

ParseException

**说明**：

1. 必须要处理的异常
   - throws向上声明
   - try-catch-finally

![image-20200305120916685](C:\Users\tiger\AppData\Roaming\Typora\typora-user-images\image-20200305120916685.png)

### 二、捕获异常

#### 2.1 对方法体中的语句，进行捕获异常（try-catch-finally）

```java
public void method(){
    try{
        //可能出现异常的语句
        int i = 0/2;
    }catch(Exception ex){
        //打印异常类型
        return;
    }finally{
        //关闭资源
    }
}
```

#### 2.2 throws（对方法抛出异常）

定义：如果方法声明的是Exception类型的异常或者是Checked Exception异常，要求方法的调用处笔记做处理。

- 继续使用throws向上（方法的调用处）声明

- 使用try-catch-finally进行处理

- 用于声明方法可能会产生的异常类型

- 写法：throws 写在方法名称后面

  说明：如果声明的是 RuntimeException 类型的异常，那么方法的调用处可处理可不处理。 

```java
public void method() throws IOException {
		File f=new File("D:\\a.txt");
		f.createNewFile();
}
```

#### 2.3 throw 抛出异常对象（写在方法内）

- 手动抛出异常对象。
- throw写在方法里。

```java
public static void show(){	
		try {
			throw new Exception();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}		
}
```



#### 2.4 继承关系中的异常声明

情况如下：

- 父类方法声明Exception类型的异常，子类在重写方法时，可声明也可以不声明。【但是如果子类重写后的方法使用super关键字调用父类的方法，那么要求必须对异常进行处理】
- 如果父类的方法没有异常，子类的方法**需要声明异常**，要求子类必须自己使用try-catch处理，或者给父类加上异常的声明。
- 如果子类重写父类的方法，产生RuntimeException异常，那么可以不进行处理。

#### 

### 三、自定义异常

#### 3.1 定义

​		在程序中，可能会遇到任何标准异常类都没有充分的描述清楚问题，这种情况下可以创建自己的异常类。

#### 3.2 步骤

- 继承Exception或RuntimeException
- 定义构造方法
- 使用异常

#### 3.3 案例

```java
public class MyException extends Exception {
	public MyException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public MyException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}
}
```

使用自定义异常：跟普通异常使用方式一样（throw,throws,try-catch-finally）